package com.projjee;

// Generated 28 janv. 2015 08:09:53 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 * Commentaire generated by hbm2java
 */
public class Commentaire implements java.io.Serializable {

	private int idCommentaire;
	private Image image;
	private User user;
	private String commentaire;
	private String comDateMaj;
	private String comDateAjout;
	
	private DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
	private Date today = Calendar.getInstance().getTime();
	private String reportDate = df.format(today);

	public Commentaire() {
	}

	public Commentaire(Image image, User user,
			String commentaire) {
		this.image = image;
		this.user = user;
		this.commentaire = commentaire;
		this.comDateAjout = reportDate;
		this.comDateMaj = reportDate;
	}

	public Commentaire(Image image, User user,
			String commentaire, String comDateMaj, String comDateAjout) {
		this.image = image;
		this.user = user;
		this.commentaire = commentaire;
		this.comDateMaj = comDateMaj;
		this.comDateAjout = comDateAjout;
		this.comDateAjout = reportDate;
		this.comDateMaj = reportDate;
	}

	public int getIdCommentaire() {
		return this.idCommentaire;
	}

	public void setIdCommentaire(int idCommentaire) {
		this.idCommentaire = idCommentaire;
		this.comDateMaj = reportDate;
	}

	public Image getImage() {
		return this.image;
	}

	public void setImage(Image image) {
		this.image = image;
		this.comDateMaj = reportDate;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
		this.comDateMaj = reportDate;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
		this.comDateMaj = reportDate;
	}

	public String getComDateMaj() {
		return this.comDateMaj;
	}

	public void setComDateMaj(String comDateMaj) {
		this.comDateMaj = comDateMaj;
	}

	public String getComDateAjout() {
		return this.comDateAjout;
	}

	public void setComDateAjout(String comDateAjout) {
		this.comDateAjout = comDateAjout;
		this.comDateMaj = reportDate;
	}

}
