package com.projjee;

// Generated 28 janv. 2015 08:09:53 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	private int idImage;
	private User user;
	private Categorie categorie;
	private String urlImage;
	private String nomImage;
	private String descriptionImage;
	private String imageDateMaj;
	private String imageDateAjout;
	private Integer imageNbView;
	private Integer imageNbDl;
	private Integer imageSize;
	private String imageDimension;
	private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);
	
	private DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
	private Date today = Calendar.getInstance().getTime();        
	private String reportDate = df.format(today);

	public Image() {
	}

	public Image(User user, Categorie categorie, String urlImage) {
		this.user = user;
		this.categorie = categorie;
		this.urlImage = urlImage;
		this.imageDateMaj = reportDate;
		this.imageDateAjout = reportDate;
	}

	public Image(User user, Categorie categorie, String urlImage, String nomImage, String descImage) {
		this.user = user;
		this.categorie = categorie;
		this.urlImage = urlImage;
		this.nomImage = nomImage;
		this.descriptionImage = descImage;
		this.imageDateMaj = reportDate;
		this.imageDateAjout = reportDate;
	}
	
	public Image(User user, Categorie categorie, String urlImage, String nomImage, String descImage, long size) {
		this.user = user;
		this.categorie = categorie;
		this.urlImage = urlImage;
		this.nomImage = nomImage;
		this.descriptionImage = descImage;
		this.imageSize = (int)size;
		this.imageDateMaj = reportDate;
		this.imageDateAjout = reportDate;
	}
	
	public Image(User user, Categorie categorie, String urlImage, 
			String nomImage, String descImage, long size, String dimension) {
		this.user = user;
		this.categorie = categorie;
		this.urlImage = urlImage;
		this.nomImage = nomImage;
		this.descriptionImage = descImage;
		this.imageSize = (int)size;
		this.imageDimension = dimension;
		this.imageDateMaj = reportDate;
		this.imageDateAjout = reportDate;
	}
	
	public Image(User user, Categorie categorie, String urlImage,
			String nomImage, String descriptionImage, String imageDateMaj,
			String imageDateAjout, Integer imageNbView, Integer imageNbDl,
			Integer imageSize, String imageDimension,
			Set<Commentaire> commentaires) {
		this.user = user;
		this.categorie = categorie;
		this.urlImage = urlImage;
		this.nomImage = nomImage;
		this.descriptionImage = descriptionImage;
		this.imageDateMaj = reportDate;
		this.imageDateAjout = reportDate;
		this.imageNbView = imageNbView;
		this.imageNbDl = imageNbDl;
		this.imageSize = imageSize;
		this.imageDimension = imageDimension;
		this.commentaires = commentaires;
	}

	public int getIdImage() {
		return this.idImage;
	}

	public void setIdImage(int idImage) {
		this.idImage = idImage;
		this.imageDateMaj = reportDate;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
		this.imageDateMaj = reportDate;
	}

	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
		this.imageDateMaj = reportDate;
	}

	public String getUrlImage() {
		return this.urlImage;
	}

	public void setUrlImage(String urlImage) {
		this.urlImage = urlImage;
		this.imageDateMaj = reportDate;
	}

	public String getNomImage() {
		return this.nomImage;
	}

	public void setNomImage(String nomImage) {
		this.nomImage = nomImage;
		this.imageDateMaj = reportDate;
	}

	public String getDescriptionImage() {
		return this.descriptionImage;
	}

	public void setDescriptionImage(String descriptionImage) {
		this.descriptionImage = descriptionImage;
		this.imageDateMaj = reportDate;
	}

	public String getImageDateMaj() {
		return this.imageDateMaj;
	}

	public void setImageDateMaj(String imageDateMaj) {
		this.imageDateMaj = imageDateMaj;
	}

	public String getImageDateAjout() {
		return this.imageDateAjout;
	}

	public void setImageDateAjout(String imageDateAjout) {
		this.imageDateAjout = imageDateAjout;
		this.imageDateMaj = reportDate;
	}

	public Integer getImageNbView() {
		return this.imageNbView;
	}

	public void setImageNbView(Integer imageNbView) {
		this.imageNbView = imageNbView;
		this.imageDateMaj = reportDate;
	}

	public Integer getImageNbDl() {
		return this.imageNbDl;
	}

	public void setImageNbDl(Integer imageNbDl) {
		this.imageNbDl = imageNbDl;
		this.imageDateMaj = reportDate;
	}

	public Integer getImageSize() {
		return this.imageSize;
	}

	public void setImageSize(Integer imageSize) {
		this.imageSize = imageSize;
		this.imageDateMaj = reportDate;
	}

	public String getImageDimension() {
		return this.imageDimension;
	}

	public void setImageDimension(String imageDimension) {
		this.imageDimension = imageDimension;
		this.imageDateMaj = reportDate;
	}

//	public Set<Commentaire> getCommentaires() {
//		List<Commentaire> tempList = new ArrayList(this.commentaires);
//		Commentaire[] sortedList = new Commentaire[]{};
//		
//		for (Commentaire item  : tempList)
//		{
//			sortedList = addElement(sortedList, item);
//		}
//		
//		Arrays.sort(sortedList, Image.CommentaireDateComparator);
//		
//		Set<Commentaire> sortedSetCom = new HashSet<Commentaire>(0);
//		
//		for (Commentaire item  : sortedList)
//		{
//			sortedSetCom.add(item);
//		}
//		
//		return sortedSetCom;
//	}
	
	public Set<Commentaire> getCommentaires() {
		return this.commentaires;
	}

	public void setCommentaires(Set<Commentaire> commentaires) {
		this.commentaires = commentaires;
		this.imageDateMaj = reportDate;
	}
	
//	public static Comparator<Commentaire> CommentaireDateComparator = new Comparator<Commentaire>() {
//
//		public int compare(Commentaire com1, Commentaire com2) {
//
//			String comDate1 = com1.getComDateAjout().toUpperCase();
//			String comDate2 = com2.getComDateAjout().toUpperCase();
//
//			//ascending order
//			//return comDate1.compareTo(comDate2);
//
//			//descending order
//			return comDate2.compareTo(comDate1);
//		}
//
//	};
//
//	public int compareTo(Image compareFruit) {
//		 
//		int compareQuantity = ((Image) compareFruit).getIdImage(); 
// 
//		//ascending order
//		return this.idImage - compareQuantity;
// 
//		//descending order
//		//return compareQuantity - this.quantity;
// 
//	}
//	
//	Commentaire[] addElement(Commentaire[] org, Commentaire added) {
//		Commentaire[] result = Arrays.copyOf(org, org.length +1);
//	    result[org.length] = added;
//	    return result;
//	}

}
